In [7]:
import numpy as numpy
import numpy as np

a1 = np.array([1, 2, 3, 4, 5])
print(a1)
print("Dimension:", a1.ndim)

a2 = np.array([[1, 2, 3], [4, 5, 6]])
print(a2)
print("Dimension:", a2.ndim)

a3 = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(a3)
print("Dimension:", a3.ndim)




[1 2 3 4 5]
Dimension: 1
[[1 2 3]
 [4 5 6]]
Dimension: 2
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
Dimension: 3


In [12]:
int_array = np.array([1, 2, 3, 4, 5])

float_array = int_array.astype(float)

print("Original array (int):", int_array)
print("Converted array (float):", float_array)


Original array (int): [1 2 3 4 5]
Converted array (float): [1. 2. 3. 4. 5.]


In [14]:
import numpy as np

data = """17 8 9 5 15
        14 19 2 3 7
        18 1 6 25 0"""

rows = data.strip().split('\n')
matrix = [list(map(int, row.split())) for row in rows]

numpy_matrix = np.array(matrix)

print(numpy_matrix)


[[17  8  9  5 15]
 [14 19  2  3  7]
 [18  1  6 25  0]]


In [15]:
matrix = np.array([[17, 8, 9, 5, 15],
                   [14, 19, 2, 3, 7],
                   [18, 1, 6, 25, 0]])

value_0 = matrix[2, 4]  
value_3 = matrix[1, 3]  
value_19 = matrix[1, 1]  

print("Value 0:", value_0)
print("Value 3:", value_3)
print("Value 19:", value_19)


Value 0: 0
Value 3: 3
Value 19: 19


In [17]:
matrix = np.array([[17, 8, 9, 5, 15],
                   [14, 19, 2, 3, 7],
                   [18, 1, 6, 25, 0]])


a = matrix[1, 2] 
print(a)

2


In [18]:
b = matrix[0, 4] 
print(b)

15


In [20]:
    b = np.array([[17, 8, 9, 5, 15],
              [14, 19, 2, 3, 7],
              [18, 1, 6, 25, 0]])


r1 = b[0, 0:2]  
r2 = b[1, 0:2]  

print("Elements from row 1:", r1)
print("Elements from row 2:", r2)



Elements from row 1: [17  8]
Elements from row 2: [14 19]


In [21]:
r3 = b[1, 1:3] 
r4 = b[2, 1:3]  

print("Elements from row 2:", r3)
print("Elements from row 3:", r4)

Elements from row 2: [19  2]
Elements from row 3: [1 6]


In [22]:
r5 = b[0, 3:5] 
r6 = b[1:3, 2:5]  

print("Elements from row 1:", r5)
print("Elements from row 2 and 3:", r6)


Elements from row 1: [ 5 15]
Elements from row 2 and 3: [[ 2  3  7]
 [ 6 25  0]]


In [23]:
identity_matrix = np.identity(5)
print(identity_matrix)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [24]:
#  Print 10 evenly spaced points from 0 to 10.

points = np.linspace(0, 10, num=10)
print(points)


[ 0.          1.11111111  2.22222222  3.33333333  4.44444444  5.55555556
  6.66666667  7.77777778  8.88888889 10.        ]


In [31]:
# Print 10 int value within range of 9 to 900

int_values = np.random.randint(9, 901, size=10)
print(int_values)


[811 300 252 177 482 203 574 417 218 133]


In [32]:
# From this nested list, lst = [[12,3,5],[98,56,78],[5,8,9]] make a numpy array ?


lst = [[12, 3, 5], [98, 56, 78], [5, 8, 9]]
numpy_array = np.array(lst)

print(numpy_array)


[[12  3  5]
 [98 56 78]
 [ 5  8  9]]


In [33]:
#  Lst = [12,3,5,98,56,78,5,8,9] from this list make a 3*3 matrix? 


Lst = [12, 3, 5, 98, 56, 78, 5, 8, 9]
matrix = np.array(Lst).reshape(3, 3)

print(matrix)


[[12  3  5]
 [98 56 78]
 [ 5  8  9]]


In [36]:
#  ARR = np.array([5,8,7,96,54,0,42]) from this array print only those numbers greater than 10


ARR = np.array([5, 8, 7, 96, 54, 0, 42])

for num in ARR:
    if num > 10:
        print(num)

    


96
54
42


In [37]:
#  Print 10 evenly spaced points from 40 to 80 and also print step size

import numpy as np

start = 40
stop = 80
num_points = 10

points = np.linspace(start, stop, num_points)
step_size = (stop - start) / (num_points - 1)

print("Evenly spaced points:", points)
print("Step size:", step_size)


Evenly spaced points: [40.         44.44444444 48.88888889 53.33333333 57.77777778 62.22222222
 66.66666667 71.11111111 75.55555556 80.        ]
Step size: 4.444444444444445


In [38]:
# What will be the output of the following? a) range(5,10.5) b) arange(5,10.5)


array_b = np.arange(5, 10.5)
print(array_b)


[ 5.  6.  7.  8.  9. 10.]


In [39]:
# Make an array using arange functions, x=np.arange(12) and reshape the array in 3*4, 4*3, 2*6, 6*2 matrix.

x = np.arange(12)


matrix_3x4 = x.reshape(3, 4)
print("3x4 matrix:")
print(matrix_3x4)

matrix_4x3 = x.reshape(4, 3)
print("4x3 matrix:")
print(matrix_4x3)

matrix_2x6 = x.reshape(2, 6)
print("2x6 matrix:")
print(matrix_2x6)

matrix_6x2 = x.reshape(6, 2)
print("6x2 matrix:")
print(matrix_6x2)


3x4 matrix:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
4x3 matrix:
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
2x6 matrix:
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
6x2 matrix:
[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]]


In [40]:
# Convert this list lst = [12,3,5,98,56,78,5] to an array and add 100 with each element.

lst = [12, 3, 5, 98, 56, 78, 5]
array = np.array(lst)  # Convert the list to a NumPy array
array_plus_100 = array + 100

print("Original array:", array)
print("Array after adding 100:", array_plus_100)



Original array: [12  3  5 98 56 78  5]
Array after adding 100: [112 103 105 198 156 178 105]


In [41]:
# Convert this list lst = [12,3,5,9,8,20] to an array and square root each and every element

import numpy as np

lst = [12, 3, 5, 9, 8, 20]
array = np.array(lst)  # Convert the list to a NumPy array
array_sqrt = np.sqrt(array)

print("Original array:", array)
print("Array after square root:", array_sqrt)


Original array: [12  3  5  9  8 20]
Array after square root: [3.46410162 1.73205081 2.23606798 3.         2.82842712 4.47213595]


In [42]:
#  What is the total sum,row-wise sum and column-wise sum of this matrix? ([[ 0, 6], [ 1, 7], [ 2, 8], [ 3, 9], [ 4, 10], [ 5, 11]]) 

matrix = np.array([[0, 6], [1, 7], [2, 8], [3, 9], [4, 10], [5, 11]])

total_sum = np.sum(matrix)
row_sum = np.sum(matrix, axis=1)
col_sum = np.sum(matrix, axis=0)

print("Matrix:")
print(matrix)
print("Total sum:", total_sum)
print("Row-wise sum:", row_sum)
print("Column-wise sum:", col_sum)


Matrix:
[[ 0  6]
 [ 1  7]
 [ 2  8]
 [ 3  9]
 [ 4 10]
 [ 5 11]]
Total sum: 66
Row-wise sum: [ 6  8 10 12 14 16]
Column-wise sum: [15 51]


In [44]:
# . Multiply this two matrix, m1=np.array([[23, 32], [54, 14]]), m2=np.array([[32, 20], [25, 33]])

import numpy as np

m1 = np.array([[23, 32], [54, 14]])
m2 = np.array([[32, 20], [25, 33]])

result = np.dot(m1, m2)

print("Matrix m1:", m1)
print("Matrix m2:", m2)
print("Matrix multiplication result:", result)



Matrix m1: [[23 32]
 [54 14]]
Matrix m2: [[32 20]
 [25 33]]
Matrix multiplication result: [[1536 1516]
 [2078 1542]]


In [46]:
# Calculate Euclidean Distance between this two point p1=np.array((1, 5, 3)), p2=np.array((1, 2, 2))

p1 = np.array((1, 5, 3))
p2 = np.array((1, 2, 2))

distance = np.linalg.norm(p2 - p1)

print("Point p1:", p1)
print("Point p2:", p2)
print("Euclidean distance:", distance)


Point p1: [1 5 3]
Point p2: [1 2 2]
Euclidean distance: 3.1622776601683795


In [47]:
#  Convert this list into a numpy array, a1=np.array([[1,2,3],[4,5,6],[7,8,9]]) and find out the mean row wise and axis wise? 

a1 = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

mean_row_wise = np.mean(a1, axis=1)
mean_column_wise = np.mean(a1, axis=0)

print("Array a1:")
print(a1)
print("Mean row-wise:", mean_row_wise)
print("Mean column-wise:", mean_column_wise)


Array a1:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Mean row-wise: [2. 5. 8.]
Mean column-wise: [4. 5. 6.]


In [48]:
#  what will be the total mean, row wise mean and column wise mean of this array, a = np.array([[1, np.nan,4,5], [3, 4, np.nan,5],[8, 7, np.nan,9]])

a = np.array([[1, np.nan, 4, 5],
              [3, 4, np.nan, 5],
              [8, 7, np.nan, 9]])

total_mean = np.nanmean(a)
row_mean = np.nanmean(a, axis=1)
column_mean = np.nanmean(a, axis=0)

print("Array a:")
print(a)
print("Total mean:", total_mean)
print("Row-wise mean:", row_mean)
print("Column-wise mean:", column_mean)


Array a:
[[ 1. nan  4.  5.]
 [ 3.  4. nan  5.]
 [ 8.  7. nan  9.]]
Total mean: 5.111111111111111
Row-wise mean: [3.33333333 4.         8.        ]
Column-wise mean: [4.         5.5        4.         6.33333333]
