In [55]:
for element in [1, 2, 3]:
    print(element)


1
2
3


In [ ]:
# object oriented programming
#class - template
#object - instance
class Abc:
    pass
x = Abc()
x

In [ ]:
# A class may have
### 1. methods and functions
# user defined function
# special methods/dendurs/magic methods
# decorated methods 

##### inheritance

# single


In [ ]:
class Abc():
    a = 10
    b = 20
    def show(p):
        print(p.a,Abc.b)
        
x = Abc()
print(x)
x.show()  

10 20


In [ ]:
x.a = 45
y.a = 55
Abc.b = 100


In [ ]:
y = Abc()
z = Abc()


In [ ]:
y.show()

10 100


In [ ]:
z.show()

10 100


In [ ]:
x.show()
y.show()
z.show()

45 100
10 100
10 100


In [ ]:
class Abc():
    a = 10
    b = 20
    def __init__(self,a = 10,b = 20):
        self.a = b
        Abc.b = b
    def __str__(self) -> str:
        return "hi"
    
    #def __call__(self,*args: Any, **:Any) -> Any:
     #   return sum(Args)
        
    def show(self):
        print(self.a, Abc.b)
        
x = Abc()
print(x)
y = Abc(a = 30)
z = Abc(a = 35)
x.show(); y.show(); z.show()
w = Abc(b = 30)
x.show(); y.show(); z.show(); w.show()
#x(5,8,2,5,7,4)
            

hi
20 20
20 20
20 20
20 30
20 30
20 30
30 30


In [54]:
class Pqr(Abc):
    
    def __init__(Self, a=10, b=20):
        super().__init__(a,b)
    def simple(Self):
        print("its simple")
    def show(self):
        print(self.a)    

p = Pqr(a = 30)
p.simple()

p.show() 
#p()       

its simple
20


In [2]:
#############
## GUI Development  ##
import tkinter as Ktr

app = Ktr.Tk(__name__)
app.geometry("400x400")
app.title("My First GUI")

var1 = Ktr.variable()
var1 = set("Initial Value")

#a = Ktr.Label(app, text = "Mera Phela Text")
a = Ktr.Label(app, textvariable-var1)
a.grid(row=0,column=1)

a.pack()

Ktr.Label(app, text = "ye dusera threka ha").pack()


app.mainloop()

AttributeError: module 'tkinter' has no attribute 'variable'

In [1]:
import tkinter
m = tkinter.Tk()


m.mainloop()


In [2]:
import tkinter as tk
r = tk.Tk()
r.title('Counting Seconds')
button = tk.Button(r, text='Stop', width=25, command=r.destroy)
button.pack()
r.mainloop()


In [3]:
from tkinter import *
master = Tk()
w = Canvas(master, width=40, height=60)
w.pack()
canvas_height=20
canvas_width=200
y = int(canvas_height / 2)
w.create_line(0, y, canvas_width, y )
mainloop()


In [6]:
from tkinter import *
master = Tk()
Label(master, text='First Name').grid(row=0)
Label(master, text='Last Name').grid(row=1)
e1 = Entry(master)
e2 = Entry(master)
e1.grid(row=0, column=1)
e2.grid(row=1, column=1)
mainloop()



In [7]:
from tkinter import *

root = Tk()
frame = Frame(root)
frame.pack()
bottomframe = Frame(root)
bottomframe.pack( side = BOTTOM )
redbutton = Button(frame, text = 'Red', fg ='red')
redbutton.pack( side = LEFT)
greenbutton = Button(frame, text = 'Brown', fg='brown')
greenbutton.pack( side = LEFT )
bluebutton = Button(frame, text ='Blue', fg ='blue')
bluebutton.pack( side = LEFT )
blackbutton = Button(bottomframe, text ='Black', fg ='black')
blackbutton.pack( side = BOTTOM)
root.mainloop()


In [8]:
from tkinter import *
root = Tk()
w = Label(root, text='AI And DL Intern')
w.pack()
root.mainloop()


In [9]:

from tkinter import *

top = Tk()
Lb = Listbox(top)
Lb.insert(1, 'Python')
Lb.insert(2, 'Java')
Lb.insert(3, 'C++')
Lb.insert(4, 'Any other')
Lb.pack()
top.mainloop()


In [10]:
from tkinter import *

top = Tk()
mb = Menubutton ( top, text = "AI And DL")
mb.grid()
mb.menu = Menu ( mb, tearoff = 0 )
mb["menu"] = mb.menu
cVar = IntVar()
aVar = IntVar()
mb.menu.add_checkbutton ( label ='Contact', variable = cVar )
mb.menu.add_checkbutton ( label = 'About', variable = aVar )
mb.pack()
top.mainloop()


In [3]:
!python -m pip install numpy



[notice] A new release of pip is available: 23.0.1 -> 23.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [4]:
import numpy as np

In [5]:
# numpt datatypes
## Numpy.nd.array

a = np.array([3,8,4,89,45])
a

array([ 3,  8,  4, 89, 45])

In [6]:
type(a)

numpy.ndarray

In [10]:
print(a.shape)
print(a.size)
print(a.dtype)
len(a)

(5,)
5
int32


5

In [11]:
def show_array(arr):
    print('Array:', arr, sep='\n')
    print('Type:', type(arr))
    print('Shape:', arr.shape)
    print('Size:', arr.size)
    print('DType:', arr.dtype)
    print('Length:', len(arr))
    print('Dimension:', arr.ndim)

In [12]:

# 10  11  13  14
# 45  22   9   2
# 6    5   1   8
b = np.array([[10,11,13,14], [45,22,9,2], [6,5,1,8]])
show_array(b)

Array:
[[10 11 13 14]
 [45 22  9  2]
 [ 6  5  1  8]]
Type: <class 'numpy.ndarray'>
Shape: (3, 4)
Size: 12
DType: int32
Length: 3
Dimension: 2


In [13]:
b[2,:]

array([6, 5, 1, 8])

In [14]:
 # 100  110  130  140
                # 145  122   19   12
                # 16    15   11   18
# 10  11  13  14
# 45  22   9   2
# 6    5   1   8
c = np.array([[[10,100],[11,110],[13,130],[14,140]], 
              [[45,145],[22,122],[9,19],[2,12]],
              [[6,16],[5,15],[1,11],[8,18]]])
show_array(c)

Array:
[[[ 10 100]
  [ 11 110]
  [ 13 130]
  [ 14 140]]

 [[ 45 145]
  [ 22 122]
  [  9  19]
  [  2  12]]

 [[  6  16]
  [  5  15]
  [  1  11]
  [  8  18]]]
Type: <class 'numpy.ndarray'>
Shape: (3, 4, 2)
Size: 24
DType: int32
Length: 3
Dimension: 3


In [15]:
# Array Operations
### 1. Item Accessing: Subscripting, Slicing
### 2. Item Assignment
### 3. Item Insertion
### 4. Item Deletion
### 5. Arithmetic

b

array([[10, 11, 13, 14],
       [45, 22,  9,  2],
       [ 6,  5,  1,  8]])

In [16]:
b[0,0]
b[1, -3:]
b[:, -2]
b[:, -2:-1]


array([[13],
       [ 9],
       [ 1]])

In [17]:
[[10,11,13,14], [45,22,9,2], [6,5,1,8]]
# b[0][0]
# b[1][1:]
# subscripting [1st, 2nd, 3rd , ....., nth dim]
# subscripting [1st:1st end: stepsize, 2nd, 3rd , ....., nth dim]
b[0,0]
b[1, -3:]
b[:, -2]
b[:, -2:-1]

array([[13],
       [ 9],
       [ 1]])

In [18]:
b[:, -2].shape

(3,)

In [19]:
k = [3,5,7,3,7,89,3]
k[2:3]

[7]

In [20]:
print(b[-1:,:])
print(c[:1, :2, :])
print(c[:, 1:2, :1])
print(c[-2:, -1:, :1])
print(c[:2, -2:, :])

[[6 5 1 8]]
[[[ 10 100]
  [ 11 110]]]
[[[11]]

 [[22]]

 [[ 5]]]
[[[2]]

 [[8]]]
[[[ 13 130]
  [ 14 140]]

 [[  9  19]
  [  2  12]]]


In [21]:
# Item Assignment
b[1,2] = 90
b

array([[10, 11, 13, 14],
       [45, 22, 90,  2],
       [ 6,  5,  1,  8]])

In [22]:
# Item Insertion
a = np.append(a, 80)
a

array([ 3,  8,  4, 89, 45, 80])

In [23]:
np.append(b, [[9,90,900,9000]], axis = 0)  # axis = 0-> Row, 1->Col

array([[  10,   11,   13,   14],
       [  45,   22,   90,    2],
       [   6,    5,    1,    8],
       [   9,   90,  900, 9000]])

In [24]:
np.append(b, [[9],[90],[900]], axis = 1)

array([[ 10,  11,  13,  14,   9],
       [ 45,  22,  90,   2,  90],
       [  6,   5,   1,   8, 900]])

In [25]:
# Item Deletion
# del a[-1]  # This won't work
b1 = b.copy()

In [26]:
b1

array([[10, 11, 13, 14],
       [45, 22, 90,  2],
       [ 6,  5,  1,  8]])

In [27]:
np.delete(b1, 0, axis=0)

array([[45, 22, 90,  2],
       [ 6,  5,  1,  8]])

In [28]:
# Arithmetic Operations

In [29]:
b1 -20

array([[-10,  -9,  -7,  -6],
       [ 25,   2,  70, -18],
       [-14, -15, -19, -12]])

In [30]:
b1 + 20

array([[ 30,  31,  33,  34],
       [ 65,  42, 110,  22],
       [ 26,  25,  21,  28]])

In [31]:
# More functions to create array
##################################
## np.array()
## np.arange()  -> array version of range func, also allows float
## np.linspace() -> start, end, no. of items
## np.ones() -> generate all values as '1'
## np.zeros() -> generate all values as '0'
## np.random.random()
## np.random.randint()

In [32]:
b1.reshape(2,6,1,1)

array([[[[10]],

        [[11]],

        [[13]],

        [[14]],

        [[45]],

        [[22]]],


       [[[90]],

        [[ 2]],

        [[ 6]],

        [[ 5]],

        [[ 1]],

        [[ 8]]]])

In [33]:
b.dtype

dtype('int32')

In [34]:

b.astype(float)

array([[10., 11., 13., 14.],
       [45., 22., 90.,  2.],
       [ 6.,  5.,  1.,  8.]])

In [35]:

b.astype('uint16')

array([[10, 11, 13, 14],
       [45, 22, 90,  2],
       [ 6,  5,  1,  8]], dtype=uint16)

In [36]:
np.ones((3,4), dtype='int') * 5

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])